import Foundation

enum MonsterSprites {
    static let bat = PixelSprite([
        "........................",
        "........................",
        "........KKKKKK..........",
        ".......KUUUUUUK.........",
        ".......KUKKKKUK.........",
        "......KUUUUUUUUK........",
        "......KUKWWKWWKK........",
        "KKK..KUKWKKWKKUK..KKK...",
        "KuuKKUUKKUUUUKKUUKKuuK..",
        "KuuuUUUUUUUUUUUUUUuuuK..",
        "KuuuUUUKKKKKKKKUUUuuuK..",
        "KKuuUUUKWKKKKWKUUUuuKK..",
        ".KKuKUUKKKKKKKKUUUKuKK..",
        "..KKKUUUUUUUUUUUUKKKK...",
        ".....KKUUUUUUUUUKK......",
        ".......KUUUUUUUK........",
        "........KKKKKKK.........",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................"
    ])

    static let goblin = PixelSprite([
        "........................",
        "........................",
        "........KKKKKKK.........",
        ".......KAAAAAAAK........",
        "......KAAYWWYAYWWYAK....",
        "......KAAYKKYAYKKYAK....",
        "......KAAAAKKKAAAAAK....",
        "......KAAAKRRRKAAAAK....",
        ".......KKAAAAAAAAKK.....",
        "........KAAAAAAAK.......",
        "......KKKAAAAAAAKKK.....",
        ".....KAAAAAAAAAAAAK.....",
        "....KAAAAAAAAAAAAAAK....",
        "....KAAaaaaaaaaaaaAK....",
        "....KAAaaaaaaaaaaaAK....",
        "....KAAAAAAAAAAAAAAK....",
        ".....KKAAAAAAAAAAKK.....",
        "......KAAAAAAAAAAK......",
        "......KAAKKKKKKAAAK.....",
        "......KAAK....KAAK......",
        "......KAAK....KAAK......",
        "......KKKK....KKKK......",
        "........................",
        "........................"
    ])

    static let skeleton = PixelSprite([
        "........................",
        "........................",
        "........KKKKKKKK........",
        ".......KWWWWWWWWK.......",
        "......KWWKKKKKKWWK......",
        "......KWKKWWWWKKWK......",
        "......KWKWKKKKWKWK......",
        "......KWKWKKKKWKWK......",
        "......KWWKKKKKKWWK......",
        ".......KWWKWWKWWK.......",
        "........KWWKKWWK........",
        "........KKKKKKKK........",
        "......KKKKKKKKKKKK......",
        ".....KWWKWWWWWWKWWK.....",
        "....KWWKKKWWWWKKKWWK....",
        "....KWWWWKWWWWKWWWWK....",
        "....KWWWKKKKKKKKWWWK....",
        ".....KKKWWWWWWWWKKK.....",
        ".......KWWKKKKWWK.......",
        ".......KWWK..KWWK.......",
        "......KWWWK..KWWWK......",
        "......KKKKK..KKKKK......",
        "........................",
        "........................"
    ])
}
